laravel_test_mini_blog/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::auth();
Route::group(['middleware' => ['web']], function () {

    Route::get('/', ['uses'=>'ArticleController@index', 'as'=>'home']);
    Route::get('/{author}/articles', ['uses'=>'IndexController@author', 'as'=>'author']);
    Route::get('/about', ['uses'=>'IndexController@about', 'as'=>'about']);

    Route::group(['middleware' => ['auth']], function() {

        //-------Trash--------
        Route::get('articles/trash', ['uses'=>'IndexController@trash', 'as'=>'trash']);
        Route::patch('articles/trash/{article_id}', ['uses'=>'ArticleController@restore_article', 'as'=>'restore_article']);
        Route::delete('article/confirm_destroy/{article_id}', ['uses'=>'ArticleController@confirm_destroy', 'as'=>'article.confirm_destroy']);
        //--------------------
        Route::resource('article','ArticleController', ['except' => ['index','show']]);
        //----User profile----
        Route::get('/profile', ['uses'=>'UserController@profile', 'as'=>'profile']);
        Route::get('/profile/edit', ['uses'=>'UserController@edit', 'as'=>'edit_user']);
        Route::post('/profile/edit', ['uses'=>'UserController@update', 'as'=>'update_user']);
        Route::get('/profile/passwords', ['uses'=>'UserController@edit_password', 'as'=>'edit_password']);
        Route::post('/profile/passwords', ['uses'=>'UserController@update_password', 'as'=>'update_password']);
        //--------------------
        Route::post('/get_experience','UserController@get_experience');
        Route::post('/set_experience','UserController@set_experience');
    });
    Route::get('/article/{article}', ['uses'=>'ArticleController@show', 'as'=>'article.show']);
});

laravel_test_mini_blog/app/Article.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\User;

class Article extends Model
{
    use SoftDeletes; //trait

    protected $dates=['deleted_at']; //current pointer's time

    protected $fillable = [
        'id', 'text', 'title', 'created_at'
    ];

    public function users() {
        return $this->belongsToMany('App\User','article_user')->withTimestamps();
    }

    public function isAuthor($user)
    {
        if ($user) {
            if($this->trashed()) {
                return null;
            }
            if ($this->users()->find($user->id)) {
                return true;
            } else {
                return false;
            }
        }
        return'mismatch';
    }
}

laravel_test_mini_blog/app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\ArticlesRepository;
use App\Article;
use App\User;
use Auth;

class ArticleController extends SiteController
{
    public function __construct(ArticlesRepository $article_rep)
    {
        parent::__construct();
        $this->template = 'index';
        $this->article_rep = $article_rep;
    }

    public function getArticles($select = '*', $search = FALSE)
    {
        $articles = $this->article_rep->get($select, $search);
        return $articles;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search_input = $request->has('search')?$request->input('search'):null;
        $this->title = "Main";
        if ($search_input) {
            $articles = $this->getArticles("*",[$search_input,['title','text']]);
        } else {
            $articles = $this->getArticles();
        }
        $data = [];
        $data ['title'] = $this->title;
        $data ['articles'] = $articles;
        $data ['auth_user'] = Auth::user();
        $this->content = view('articles.index', $data)->render();
        return $this->renderOutput();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->title = "Create article";
        $data = [];
        $data ['title'] = $this->title;
        $data ['authors'] = User::select('*')->where('id', '<>', Auth::user()->id)->get();
        $this->content = view('articles.create', $data)->render();
        return $this->renderOutput();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'text' => 'required',
            'title' => 'required',
        ]);
        $result = $this->article_rep->addArticle($request);
        if(is_array($result) && !empty($result['error'])) {
            return redirect()->back()->withInput()->with($result);
        }
        return redirect()->route('home')->with($result);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        $this->title = "Article";
        $data = [];
        $data ['article'] = $article;
        $data ['title'] = $this->title;
        $data ['auth_user'] = Auth::user();
        $this->content = view('articles.show', $data)->render();
        return $this->renderOutput();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        if(!Auth::user() || !$article->isAuthor(Auth::user())) {
            return abort('404');
        }
        $this->title = "Edit article";
        $authors_sel = array();
        $i_key = 0;
        foreach ($article->users as $author_article) {
            $authors_sel[$i_key] = $author_article->id;
            $i_key++;
        }
        $data = [];
        $data ['title'] = $this->title;
        $data ['article'] = $article;
        $data ['authors'] = User::select('*')->where('id', '<>', Auth::user()->id)->get();
        $data ['authors_sel'] = $authors_sel;
        $this->content = view('articles.edit', $data)->render();
        return $this->renderOutput();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $this->validate($request, [
            'text' => 'required',
            'title' => 'required',
        ]);
        $result = $this->article_rep->updateArticle($request, $article);
        if(is_array($result) && !empty($result['error'])) {
            return redirect()->back()->withInput()->with($result);
        }

        return redirect(route('home'))->with($result);
    }

    public function restore_article(Request $request, $article_id)
    {
        if(!Auth::user()) {
            return abort('404');
        }
        $result = $this->article_rep->restoreArticle($request, $article_id);
        if(is_array($result) && !empty($result['error'])) {
            return redirect()->back()->withInput()->with($result);
        }

        return redirect(route('trash'))->with($result);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        if(!Auth::user() || !$article->isAuthor(Auth::user())) {
            return abort('404');
        }
        $result = $this->article_rep->deleteArticle($article);

        if(is_array($result) && !empty($result['error'])) {
            return redirect()->back()->withInput()->with($result);
        }

        return redirect(route('home'))->with($result);
    }

    public function confirm_destroy(Request $request, $article_id)
    {
        if(!Auth::user()) {
            return abort('404');
        }
        $result = $this->article_rep->confirm_deleteArticle($article_id);

        if(is_array($result) && !empty($result['error'])) {
            return redirect()->back()->withInput()->with($result);
        }

        return redirect(route('trash'))->with($result);
    }
}

laravel_test_mini_blog/resources/views/articles/create.blade.php
<div class="main-content">
    <article>
        <h2 class="page-title">{{ $title }}</h2>
        <p>
            <a href="{{ route('home') }}" class="btn btn-default btn-sm btn-back" type="button">Return main</a>
        </p>
        <div class="form-body">
            <form class="form-horizontal" method="POST" action="{{ route('article.store') }}">
                {{ csrf_field() }}

                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" name="title" placeholder="Title..." value="{{ old('title') }}">
                </div>

                <div class="form-group">
                    <label for="text">Text</label>
                    <textarea class="form-control" name="text" placeholder="Text..." rows="3">{{ old('text') }}</textarea>
                </div>

                <div class="form-group">
                    <label for="sel1">The authors:</label>
                    <select class="selectpicker form-control" id="authors" name="authors[]" data-live-search="true" title="Select authors" data-hide-disabled="true" data-actions-box="true" multiple>
                        @if($authors)
                            @foreach ($authors as $author)
                                <option value="{{ $author->id }}"
                                        @if(old('authors') && in_array($author->id, old('authors')))
                                        selected="selected"
                                    @endif
                                >{{ $author->nickname }}</option>
                            @endforeach
                        @endif
                    </select>
                </div>

                <button type="submit" class="btn btn-success form-btn">Submit</button>
            </form>
        </div>
    </article>
</div><!-- main-content -->

laravel_test_mini_blog/resources/views/articles/edit.blade.php
<div class="main-content">
    <article>
        <h2 class="page-title">{{ $title }}</h2>
        <p>
            <a href="{{ route('home') }}" class="btn btn-default btn-sm btn-back" type="button">Return main</a>
        </p>
        <div class="form-body">
            <form class="form-horizontal" method="POST" action="{{ route('article.update', $article->id) }}">
                {{ csrf_field() }}
                {!! method_field('patch') !!}

                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" name="title" placeholder="Title..." value="{{ $article->title }}">
                </div>

                <div class="form-group">
                    <label for="text">Text</label>
                    <textarea class="form-control" name="text" placeholder="Text..." rows="3">{{ $article->text }}</textarea>
                </div>

                <div class="form-group">
                    <label for="sel1">The authors:</label>
                    <select class="selectpicker form-control" id="authors" name="authors[]" data-live-search="true" title="Select authors" data-hide-disabled="true" data-actions-box="true" multiple>
                        @if($authors)
                            @foreach ($authors as $author)
                                <option value="{{ $author->id }}"
                                        @if($authors_sel && in_array($author->id, $authors_sel))
                                        selected="selected"
                                    @endif
                                >{{ $author->nickname }}</option>
                            @endforeach
                        @endif
                    </select>
                </div>

                <p>The authors:
                    @foreach ($article->users as $user)
                        <span><i class="fa fa-user post-meta-icon"></i><a href="{{ route('author',$user->id) }}"> {{ $user->nickname }}</a></span>
                    @endforeach
                </p>

                <button type="submit" class="btn btn-success form-btn">Submit</button>
            </form>

        </div>
    </article>
</div><!-- main-content -->

laravel_test_mini_blog/resources/views/articles/index.blade.php
<div class="main-content">
    @if ($articles)
        @foreach ($articles as $article)
            <article>
                <a href="{{ route('article.show', $article->id) }}"><h2 class="post-title">{{ $article->title }}</h2></a>
                <div class="post-meta">
                    @foreach ($article->users as $user)
                        <span><a href="{{ route('author',$user->id) }}"><i class="fa fa-user post-meta-icon"></i> {{ $user->nickname }}</a></span>
                    @endforeach
                    <span><i class="fa fa-calendar-check-o post-meta-icon"></i> {{ \Carbon\Carbon::parse($article->created_at)->format('F d, Y')}} </span>
                </div>
                <div class="post-content">
                    <p>{{{ str_limit($article->text, $limit = 250, $end = '...') }}}</p>
                    @if ($auth_user && $article->isAuthor($auth_user))
                        <form class="form-inline" method="POST" action="{{ route('article.destroy', $article->id) }}">
                            <a href="{{ route('article.edit',$article->id) }}" class="btn btn-default btn-sm btn-category">Edit</a>
                            {{ csrf_field() }}
                            {!! method_field('delete') !!}
                            <button type="submit" class="btn btn-default btn-sm btn-back">Delete</button>
                        </form>
                    @endif
                </div>
            </article>
        @endforeach
    @else
        <article>
            <div class="post-content">
                <p>No article...</p>
            </div>
        </article>
    @endif
</div><!-- main-content -->

<!-- <div class="pagination">
  <nav>
    <ul class="pagination">
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">Next</a></li>
    </ul>
  </nav>
</div> -->

laravel_test_mini_blog/resources/views/articles/show.blade.php
<div class="main-content">
    <article>
        <h2 class="page-title">{{ $article->title }}</h2>
        <p>
            <a href="{{ route('home') }}" class="btn btn-default btn-sm btn-back" type="button">Return main</a>
        </p>
        @if ($article)
            <div class="post-meta">
                @foreach ($article->users as $user)
                    <span><a href="{{ route('author',$user->id) }}"><i class="fa fa-user post-meta-icon"></i> {{ $user->nickname }}</a></span>
                @endforeach
                <span><i class="fa fa-calendar-check-o post-meta-icon"></i> {{ \Carbon\Carbon::parse($article->created_at)->format('F d, Y')}} </span>
            </div>
            <div class="post-content">
                <p class="post">{{ $article->text }}</p>
                @if ($auth_user && $article->isAuthor($auth_user))
                    <form class="form-inline" method="POST" action="{{ route('article.destroy', $article->id) }}">
                        <a href="{{ route('article.edit',$article->id) }}" class="btn btn-default btn-sm btn-category">Edit</a>
                        {{ csrf_field() }}
                        {!! method_field('delete') !!}
                        <button type="submit" class="btn btn-default btn-sm btn-back">Delete</button>
                    </form>
                @endif
            </div>
        @else
            <div class="post-content">
                <p>No articles...</p>
            </div>
        @endif
    </article>
</div><!-- main-content -->